# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=30, verbose_name='Contact_Name')),
                ('officeNum', models.CharField(blank=True, max_length=25, null=True, verbose_name='Office_Number')),
                ('faxNum', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax_Number')),
                ('conCell', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact_Cell')),
                ('email', models.EmailField(blank=True, max_length=45, null=True, verbose_name='Email_Address')),
            ],
        ),
        migrations.CreateModel(
            name='ICR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunnel', models.CharField(max_length=12, verbose_name='Tunnel')),
                ('sysType', models.CharField(blank=True, max_length=4, null=True, verbose_name='System_Type')),
                ('scale', models.CharField(blank=True, max_length=4, null=True, verbose_name='Scale_Installed')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=9, unique=True, verbose_name='Site')),
                ('division', models.CharField(max_length=9, verbose_name='Division')),
                ('street', models.CharField(max_length=60, verbose_name='Street')),
                ('city', models.CharField(max_length=25, verbose_name='City')),
                ('state', models.CharField(max_length=15, verbose_name='State')),
                ('zzip', models.CharField(max_length=10, verbose_name='Zip_Code')),
            ],
        ),
        migrations.AddField(
            model_name='icr',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Locations', to_field='site'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Locations', to_field='site'),
        ),
    ]
