# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icr',
            name='clv490',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='CLV490'),
        ),
        migrations.AddField(
            model_name='icr',
            name='clv690',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CLV690'),
        ),
        migrations.AddField(
            model_name='icr',
            name='clvstp',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CLV_SETUP'),
        ),
        migrations.AddField(
            model_name='icr',
            name='hdd',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Hard_Drives'),
        ),
        migrations.AddField(
            model_name='icr',
            name='icr2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ICR_2'),
        ),
        migrations.AddField(
            model_name='icr',
            name='icr3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ICR_3'),
        ),
        migrations.AddField(
            model_name='icr',
            name='led',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='LED'),
        ),
        migrations.AddField(
            model_name='icr',
            name='mirror',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mirror'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='MSC'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc_gate1',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MSC_Gate1'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc_gate2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MSC_Gate2'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc_ip1',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MSC_IP1'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc_ip2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MSC_IP2'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc_mask1',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MSC_Mask1'),
        ),
        migrations.AddField(
            model_name='icr',
            name='msc_mask2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MSC_Mask2'),
        ),
        migrations.AddField(
            model_name='icr',
            name='peType',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PE_Type'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sntp_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='SNTP_IP'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sopas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SOPAS'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sspc_gate',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='SSPC_Gate'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sspc_img',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SSPC_Image'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sspc_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='SSPC_IP'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sspc_mask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='SSPC_Mask'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sspc_sntp',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='SSPC_SNTP'),
        ),
        migrations.AddField(
            model_name='icr',
            name='sspc_sw',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SSPC_SW'),
        ),
        migrations.AddField(
            model_name='icr',
            name='vms',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='VMS'),
        ),
        migrations.AddField(
            model_name='locations',
            name='HUB_dns',
            field=models.URLField(blank=True, max_length=35, null=True, verbose_name='HUB_DNS'),
        ),
        migrations.AddField(
            model_name='locations',
            name='HUB_gate',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='HUB_Gate'),
        ),
        migrations.AddField(
            model_name='locations',
            name='HUB_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='HUB_IP'),
        ),
        migrations.AddField(
            model_name='locations',
            name='HUB_mask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='HUB_Mask'),
        ),
        migrations.AddField(
            model_name='locations',
            name='HUB_ntp',
            field=models.URLField(blank=True, max_length=30, null=True, verbose_name='HUB_NTP'),
        ),
        migrations.AddField(
            model_name='locations',
            name='HUB_sw',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='HUB_SW'),
        ),
    ]
