# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160104_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HUB_dns', models.URLField(blank=True, max_length=35, null=True, verbose_name='HUB_DNS')),
                ('HUB_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='HUB_IP')),
                ('HUB_mask', models.GenericIPAddressField(blank=True, null=True, verbose_name='HUB_Mask')),
                ('HUB_gate', models.GenericIPAddressField(blank=True, null=True, verbose_name='HUB_Gate')),
                ('HUB_ntp', models.URLField(blank=True, max_length=30, null=True, verbose_name='HUB_NTP')),
                ('HUB_sw', models.CharField(blank=True, max_length=30, null=True, verbose_name='HUB_SW')),
            ],
        ),
        migrations.RemoveField(
            model_name='locations',
            name='HUB_dns',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='HUB_gate',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='HUB_ip',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='HUB_mask',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='HUB_ntp',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='HUB_sw',
        ),
        migrations.AddField(
            model_name='hub',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Locations', to_field='site'),
        ),
    ]
